<?php
class gcoder {
	var $safeZ=0.0;
	var $feedRate=40; //Inches per minute
	var $safetyOverride=1;
	var $extrudeTemp=220;
	var $platformTemp=110;
	var $extrudeSpeed=240;
	var $extruderOn=false;
	
	var $buffer;

	function __construct($extrude=220,$platform=110,$speed=240) {
		$this->extrudeTemp = $extrude;
		$this->platformTemp = $platform;
		$this->extrudeSpeed = $speed;;
	}

	function header( $buffered = true ) {
		$currentTime=date("r");
		$dateString=$currentTime;
		$out = "";	
		$out.="(Generated by PHPGcoder v1.0 ".$dateString." https://github.com/digdan/PHPGcoder )\n";
		$out .= "M104 S".$this->extrudeTemp." T0\n"; //Extruder Temprature in Celcius
		$out .= "M109 S".$this->platformTemp." T0\n"; //Platform Temprature in Celcius
		$out .= "G21\n"; //MM as units
		$out .= "G90\n"; //Absolute Positioning
		$out .= "G92 X0 Y0 Z0\n"; // Reset Position
		$out .= "M108 S".$this->extrudeSpeed."\n";
		$out .= "M6 T0\n"; //Wait to heat up.

		if ($buffered === TRUE) $this->buffer .= $out;

		return $out;		
	}

	function footer( $buffered = TRUE ) {
		$out="M02\n";
		if ($buffered == TRUE) $this->buffer .= $out;
		return $out;
	}

	function extruderOn() {
		if ($this->extruderOn == FALSE) $this->buffer .= "M101\n";
		$this->extruderOn = true;
	}

	function extruderOff() {
		if ($this->extruderOn == TRUE) $this->buffer .= "M103\n";
		$this->extruderOn = false;
	}

	function pause() {
		$out = "(Pause Program until Cycle Start button)\n";
		$out.="M71\n";
		$this->buffer .= $out;
	}

	function go($x,$y,$z,$speed=3300) {
			$this->buffer .= "G1 X{$x} Y{$y} Z{$z} F".$speed."\n";
	}
	
	function d($number) {
		return sprintf("%0.6f",$number);
	}

	function __toString() {

		$out = $this->header( false );
		$out .= $this->buffer;
		$out .= $this->footer( false );

		return $out;
	}
}
?>
